<a href="https://colab.research.google.com/github/yeshtashri/numpy_python/blob/main/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **NumPy**

In [1]:
import numpy as np
x= np.array ([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
x=[1,2,3,4]
y=(1,2,3,4)
z={1,2,3,4}
print(x,y,z)

[1, 2, 3, 4] (1, 2, 3, 4) {1, 2, 3, 4}


In [ ]:
%timeit [j**4 for j in range(1,9)]

952 ns ± 256 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
import numpy as np
%timeit np.arange(1,9)**4

1.7 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
import numpy as np
x=[1,2,3,4]
y= np.array(x)
y

array([1, 2, 3, 4])

In [5]:
l=[]
for i in range(1,5):
    int_l=int(input("enter:"))
    l.append(int_l)
print(np.array(l))

enter:10
enter:11
enter:1
enter:12
[10 11  1 12]


In [7]:
import numpy as np
x= np.array ([1,2,3,4])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [8]:
ar2= np.array([[1,2,3,4],[1,3,5,7]])#number of data in each array should be same
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 3 5 7]]
2


In [10]:
ar3= np.array([[[1,2,3],[1,3,5],[2,4,6]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [1 3 5]
  [2 4 6]]]
3


In [11]:
arn = np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


#create numpy array using numpy functions


In [13]:
#zeros array in numpy
ar_zero= np.zeros(4)
ar_zero1= np.zeros((3,4))
print(ar_zero)
print()#to add space between the output as you can see
print(ar_zero1)


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#ones array in numpy
ar_one= np.ones(4)
ar_one1= np.ones((3,4))
print(ar_one)
print()#to add space between the output as you can see
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
#empty array
ar_empty= np.empty(4)
print(ar_empty)#it will print 1's array as the most previously used memory remains and print that only.

[1. 1. 1. 1.]


In [16]:
#array with range of elements
ar_rn= np.arange(4)
print(ar_rn)

[0 1 2 3]


In [20]:
#array diagonal filled with 1's
ar_dia= np.eye(3)
ar_dia1= np.eye(4,3)
print(ar_dia)
print()
print(ar_dia1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [23]:
#create an array with values that are spaced linearlyin a specified interval
#linspace
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
