<a href="https://colab.research.google.com/github/yeshtashri/numpy_python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **NumPy**

In [1]:
import numpy as np
x= np.array ([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
x=[1,2,3,4]
y=(1,2,3,4)
z={1,2,3,4}
print(x,y,z)

[1, 2, 3, 4] (1, 2, 3, 4) {1, 2, 3, 4}


In [ ]:
%timeit [j**4 for j in range(1,9)]

952 ns ± 256 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
import numpy as np
%timeit np.arange(1,9)**4

1.7 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
import numpy as np
x=[1,2,3,4]
y= np.array(x)
y

array([1, 2, 3, 4])

In [5]:
l=[]
for i in range(1,5):
    int_l=int(input("enter:"))
    l.append(int_l)
print(np.array(l))

enter:10
enter:11
enter:1
enter:12
[10 11  1 12]


In [7]:
import numpy as np
x= np.array ([1,2,3,4])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [8]:
ar2= np.array([[1,2,3,4],[1,3,5,7]])#number of data in each array should be same
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 3 5 7]]
2


In [10]:
ar3= np.array([[[1,2,3],[1,3,5],[2,4,6]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [1 3 5]
  [2 4 6]]]
3


In [11]:
arn = np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


#create numpy array using numpy functions


In [13]:
#zeros array in numpy
ar_zero= np.zeros(4)
ar_zero1= np.zeros((3,4))
print(ar_zero)
print()#to add space between the output as you can see
print(ar_zero1)


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
#ones array in numpy
ar_one= np.ones(4)
ar_one1= np.ones((3,4))
print(ar_one)
print()#to add space between the output as you can see
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
#empty array
ar_empty= np.empty(4)
print(ar_empty)#it will print 1's array as the most previously used memory remains and print that only.

[1. 1. 1. 1.]


In [16]:
#array with range of elements
ar_rn= np.arange(4)
print(ar_rn)

[0 1 2 3]


In [20]:
#array diagonal filled with 1's
ar_dia= np.eye(3)
ar_dia1= np.eye(4,3)
print(ar_dia)
print()
print(ar_dia1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [23]:
#create an array with values that are spaced linearlyin a specified interval
#linspace
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


## create numpy arrays with random numbers

In [24]:
#rand()
import numpy as np
x= np.random.rand(5)
print(x)

[0.53290239 0.86884338 0.75722317 0.79556393 0.12532785]


In [25]:
var1=np.random.rand(2,5)
print(var1)

[[0.82212538 0.25098171 0.53958529 0.7936394  0.85829721]
 [0.55356442 0.69614789 0.53324914 0.4752303  0.55834409]]


In [26]:
#randn()
var2=np.random.randn(5)
print(var2)

[ 0.38331972  1.8544267  -1.9862313   0.09916194  0.60690254]


In [27]:
#ranf()
var3=np.random.ranf(4)
print(var3)

[0.82528401 0.69199767 0.48973243 0.64019732]


In [28]:
#randint()
var4=np.random.randint(5,20,5)#(min,max,total_numbers)
print(var4)

[16  9 10 19 15]


### data types in numpy

In [30]:
import numpy as np
var=np.array([1,2,3,4,5])
print("data type:",var.dtype)

data type: int64


In [32]:
import numpy as np
var=np.array([1.1,2,3,4,5])
print("data type:",var.dtype)

data type: float64


In [33]:
import numpy as np
var=np.array(["a","b","c"])
print("data type:",var.dtype)

data type: <U1


In [34]:
import numpy as np
var=np.array(["a",1,2,3,4,5])
print("data type:",var.dtype)

data type: <U21


In [35]:
x=np.array([1,2,3,4],dtype=np.int8)
print("data type:",x.dtype)

data type: int8


In [37]:
x=np.array([1,2,3,4],dtype= "f")
print("data type:",x.dtype)
print(x)

data type: float32
[1. 2. 3. 4.]


In [41]:
x=np.array([1,2,3,4])
new=np.float32(x)
new_one=np.int_(new)
print("data type:",x.dtype)
print("data type:",new.dtype)
print(x)
print(new)
print(new_one)

data type: int64
data type: float32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [42]:
x = np.array([1, 2, 3, 4])
new_type = x.astype(np.float64)
print("Original array:", x)
print("Original data type:", x.dtype)
print("New array:", new_type)
print("New data type:", new_type.dtype)

Original array: [1 2 3 4]
Original data type: int64
New array: [1. 2. 3. 4.]
New data type: float64
